Repository sdp-tech/SASM_BE, pull requests merged in 2023-08, with the labels that each got.

#495 #494 fix : modify preview length 100 to 150
  forest/selectors.py
Labels: task

#500 fix : disuse story address in curation create
  curations/services.py
Labels: bug

#505 #504 fix : add is_authenticated check to is_followed
  curations/selectors.py
  forest/selectors.py
  stories/selectors.py
Labels: bug

#508 #507 fix : change permission of story_included_curation
  stories/views.py
Labels: bug

#511 #510 feat : add like_cnt and created to curation detail
  curations/models.py
  curations/selectors.py
  curations/views.py
Labels: enhancement
